### ISSUE TITLE
「聯」と「聨」について

### ISSUE THREAD

**Issue by epistularum** [metasta/shinjigen-glyph#1]
「新・旧」の関連性（常用漢字ではありませんので）が間違っているのでしょうか？
残念ながら新字源を持っていないので、自ら確認することが不可能です。

```
6402	MJ020870	U+806F	聯	6402	新字	
6403	MJ020866	U+8068	聨	6402	旧字	
```

**Comment by metasta** [comment]
![0C47C61A-D553-436D-9632-E9214397CFDE](https://user-images.githubusercontent.com/188758/187040987-485e487a-97b1-4bd9-9af6-2b2ae2e322f1.JPG)
ご連絡有難うございます。ご指摘の通り6403「聨」は6402「聯」の俗字であり、旧字ではありません。私の入力作業時のミスの様です。6402「聯」が親字、6403「聨」が俗字として記載を修正しました。
